ILGOB/It-sME

ItsME.xcodeproj/project.pbxproj
Podfile
Podfile.lock

:package: (develop) PodFile에 RXKakao, SnapKit 추가(pod install 완료)

---

ItsME.xcodeproj/project.pbxproj
ItsME/Presentation/Common/AlertViewController/CommonAlertViewController.swift

- 피그마에서 디자인했던 2가지 Alert case 에 대해서 공통 모듈 구현 #16 
- <img width="500" alt="image" src="https://user-images.githubusercontent.com/81426024/202467843-47d6001a-1b36-4dde-b669-6d1cc04ca4d3.png">
- init(title:message:style:okHandler:) 생성자로 호출해서 사용하면 됩니다.

:sparkles: (feature/common) #16 Figma 에서 디자인한 Alert View 요구사항 구현

---

ItsME.xcodeproj/project.pbxproj
ItsME/GoogleService-Info.plist
ItsMETests/ItsMETests.swift
ItsMEUITests/ItsMEUITests.swift
ItsMEUITests/ItsMEUITestsLaunchTests.swift

- GoogleService-Info.plist 파일 copy 옵션으로 프로젝트에 추가해서 github에 등록
- 프로젝트 이름 변경으로 인해서 빌드되지 않던 테스트 환경 복구

GoogleService-Info.plist 파일 프로젝트에 추가, 테스트 환경 복구

---

ItsME/Presentation/Scenes/Login/LoginViewController.swift
ItsME/Presentation/Scenes/Login/LoginViewModel.swift

- 카카오 로그인 버튼 터치 시 카카오 로그인 플로우 진행
- 로그인 성공 시 홈 화면으로 이동

카카오 로그인 구현

---

ItsME.xcodeproj/project.pbxproj
ItsME/Entities/CVInfo.swift
ItsME/Entities/CoverLetter.swift
ItsME/Entities/CoverLetterItem.swift
ItsME/Entities/Resume.swift
ItsME/Entities/ResumeCategory.swift
ItsME/Entities/ResumeItem.swift
ItsME/Repositories/CVRepository.swift
ItsME/Repositories/Firebase/DatabaseReferenceManager.swift

- CV 관련 엔티티 정의
- CV 관련 Firebase DB 구조 정의
- DB 에서 데이터 가져올 수 있도록 CVRepository 정의 #25
https://console.firebase.google.com/project/itsme-30e1a/database/itsme-30e1a-default-rtdb/data/~2F

Firebase DB 연동 작업

---

ItsME/Entities/UserInfoItem.swift

- UserInfoItemIcon 열거형에 항목 추가
- 이모지를 반환하는 computed property 추가
`UserInfoItemIcon.phone.toEmoji` 처럼 사용하면 이모지가 반환됩니당

이모지 사용할 수 있도록 enum 에 구현 추가

---

ItsME/Entities/UserInfo.swift

:zap: (feature/common) Entity 구조 개선

---

ItsME.xcodeproj/project.pbxproj
ItsME/Presentation/Common/Component/ItemAddButton.swift
ItsME/Presentation/Common/Component/TotalUserInfoItemStackView.swift
ItsME/Presentation/Scenes/EditProfile/EditProfileViewController.swift
ItsME/Presentation/Scenes/EditProfile/EditProfileViewModel.swift
ItsME/Presentation/Scenes/Home/HomeViewController.swift

- 프로필 수정화면 기본 레이아웃 설정 완료
- ViewModel 일부 구현
- Debug Configuration 에서만 SwiftUI 를 import 하여 Canvas 적용

프로필 수정화면(EditProfileView) 구현 작업

---

ItsME/Presentation/Scenes/Home/HomeViewController.swift

- 다른 뷰로 넘어갔다 올 때 계속 StackView에 같은 정보가 쌓이는 에러 해결

:bug: :construction: (feature/HomeView) #42 번 이슈에 관한 오류 해결

---

ItsME.xcodeproj/project.pbxproj
ItsME/Entities/Education.swift
ItsME/Entities/UserInfo.swift
ItsME/Presentation/Common/Component/TotalUserInfoItemStackView.swift
ItsME/Presentation/Scenes/EditProfile/EditProfileViewController.swift
ItsME/Presentation/Scenes/Home/HomeViewController.swift
ItsME/Utils/Extensions/UIStackView+.swift

- 유저 정보에 학력 정보 추가
- 프로필 수정 화면에 UserInfoItems 바인딩
- #44 : 프로필 이미지 비율 조정

Edit profile 화면 구현 작업

---

ItsME.xcodeproj/project.pbxproj
ItsME/Entities/UserInfo.swift
ItsME/Presentation/Common/Component/CVCard.swift
ItsME/Presentation/Scenes/Home/HomeViewController.swift
Podfile.lock

-  이력서 카드의 높이를 따로 지정해주지 않고 위아래의 레이아웃을 잡아주어 유동적으로 설정

:construction: (feature/HomeView) 🛠️버그 발생⚙️ #47 에 관련된 문제 해결 (화면 비율에 맞게 설정)

---

ItsME.xcodeproj/project.pbxproj
ItsME/Presentation/Common/Component/ProfileInfoComponent.swift
ItsME/Presentation/Scenes/Home/HomeViewController.swift

- vStackLayout의 높이를 화면 비율에 맞게 수정하여 vStackLayout에 있는 뷰가 생성이 안되더라도 화면에 문제가 없게끔 수정
- FIXME로 추가적인 내용 작성
데이터를 못받아 왔을 경우
데이터를 성공적으로 받아왔을 경우

vStackLayout의 높이를 화면 비율에 맞게 수정하여 vStackLayout에 있는 뷰가 생성이 안되더라도 화면에 문제가 없게끔 수정

---

ItsME.xcodeproj/project.pbxproj
ItsME/Entities/EducationItem.swift
ItsME/Entities/UserInfo.swift
ItsME/Presentation/Common/Cells/EducationCell.swift
ItsME/Presentation/Common/Component/ItemAddButton.swift
ItsME/Presentation/Common/Component/TotalUserInfoItemStackView.swift
ItsME/Presentation/Common/TableView/IntrinsicHeightTableView.swift
ItsME/Presentation/Scenes/EditProfile/EditProfileViewController.swift
ItsME/Presentation/Scenes/EditProfile/EditProfileViewModel.swift
ItsME/Utils/Extensions/UIButton+.swift

- 전체적인 UI 구현 및 레이아웃 설정
- 여러 크기의 디바이스에서 정삭적으로 레이아웃 수행
- 학력에 관한 엔티티 명칭 수정 Education -> EducationItem
- 학력 테이블에서 사용할 공통 Cell 구현
- Cell 들의 높이에 따라 동적으로 높이가 변하는 TableView 구현
- EditProfileViewModel 의 Output 세분화
- 버튼의 상태에 따라 BackgroundColor 가 바뀔 수 있도록 설정하는 함수 추가 (Extension)
- 항목 추가 버튼 공통 Component 로 생성

프로필 수정 화면 작업 50% 완료

---

ItsME.xcodeproj/project.pbxproj
Podfile
Podfile.lock

:package: (feature/HomeView) Then 라이브러리 적용

---

ItsME/Presentation/Common/Cells/EducationCell.swift
ItsME/Presentation/Common/Component/ItemAddButton.swift
ItsME/Presentation/Common/Component/ProfileInfoComponent.swift
ItsME/Presentation/Common/Component/TotalUserInfoItemStackView.swift
ItsME/Presentation/Scenes/EditProfile/EditProfileViewController.swift
ItsME/Presentation/Scenes/EditProfile/EditProfileViewModel.swift
ItsME/Presentation/Scenes/Login/LoginViewController.swift
ItsME/Resources/Info.plist

- 여러 부분의 코드 개선
- 순환 참조로 인한 메모리 문제 해결
- 프로필 수정 화면 구현 진행
- 수정 완료 버튼 ViewModel 바인딩
- 프로필 사진 선택 버튼 구현
- 학력 Cell 밀어서 삭제 버튼 추가
- UI 개선

프로필 수정 화면 구현 & 코드 개선

---

ItsME.xcodeproj/project.pbxproj
ItsME/Presentation/Scenes/TotalCV/TotalCVViewController.swift
ItsME/Presentation/Scenes/TotalCV/TotalCVViewModel.swift

:sparkles: :construction: (feature/totalCV) TotalCVViewModel 구현

---

ItsME.xcodeproj/project.pbxproj
ItsME/Presentation/Common/Component/CVCard.swift
ItsME/Presentation/Common/Component/ItemAddButton.swift
ItsME/Presentation/Scenes/Home/HomeViewController.swift
ItsME/Presentation/Scenes/TotalCV/TotalCVViewController.swift
ItsME/Presentation/Scenes/TotalCV/TotalCVViewModel.swift

- CVCard 탭 시 TotalCVViewController로 화면 전환  #57

CVCard 클릭 시 화면 전환

---

ItsME/Presentation/Scenes/EditProfile/EditProfileViewController.swift
ItsME/Presentation/Scenes/EditProfile/EditProfileViewModel.swift

- Then 라이브러리 잘 되나 시험해볼겸 일부 적용
- #58 : 클로저와 self 간의 순환 참조 해결
- #60 : 이름 변경 뷰 레이아웃 잡기

이번주 목표 수행 & Then 라이브러리 적용해봄

---

ItsME/Presentation/Scenes/TotalCV/TotalCVViewController.swift

- TotalCVViewController.swift 파일에 데이터 바인딩 작업
- 네비게이션바 생성

:construction: (feature/totalCV) 데이터 바인딩 작업

---

ItsME/Presentation/Scenes/EditProfile/EditProfileViewController.swift
ItsME/Presentation/Scenes/EditProfile/EditProfileViewModel.swift

- #64: 옆으로 밀어서 Cell 삭제하는 버튼 기능 구현

프로필 수정화면 Cell 삭제 버튼 기능 구현 완료

---

ItsME.xcodeproj/project.pbxproj
ItsME/Presentation/Common/Component/CVCard.swift
ItsME/Presentation/Scenes/Home/HomeViewController.swift
ItsME/Presentation/Scenes/TotalCV/TotalCVViewController.swift
ItsME/Presentation/Scenes/TotalCV/TotalCVViewModel.swift

- #57 TotalViewModel과 HomeViewController를 subject로 연결
- #65 네비게이션 타이틀 Large로 설정

:construction: (feature/totalCV) #57 TotalViewModel과 HomeViewController를 subject로 연결, #65 네비게이션 타이틀 Large로 설정

---

ItsME.xcodeproj/project.pbxproj
ItsME/Presentation/Common/Cells/EducationCell.swift
ItsME/Presentation/Scenes/EditProfile/AddressEditing/AddressEditingViewController.swift
ItsME/Presentation/Scenes/EditProfile/BirthdayEditing/BirthdayEditingViewController.swift
ItsME/Presentation/Scenes/EditProfile/EditProfileViewController.swift
ItsME/Presentation/Scenes/EditProfile/EditProfileViewModel.swift
ItsME/Presentation/Scenes/EditProfile/EmailEditing/EmailEditingViewController.swift
ItsME/Presentation/Scenes/EditProfile/OtherItemEditing/OtherItemEditingViewController.swift
ItsME/Presentation/Scenes/EditProfile/PhoneNumberEditing/PhoneNumberEditingViewController.swift
ItsME/Presentation/Scenes/Home/HomeViewController.swift
ItsME/Utils/Extensions/Rx+Ext.swift

- 정보 수정을 위한 ViewController 파일들 생성
- UserInfoItem 추가를 위한 항목 추가 버튼 기능 구현

항목 추가 버튼 기능 구현

---

ItsME/Presentation/Scenes/EditProfile/EditProfileViewController.swift

- 프로필 수정 화면에서도 large title 적용 되는 문제 해결

:adhesive_bandage: 간단한 버그 해결

---

ItsME/Presentation/Scenes/TotalCV/TotalCVViewController.swift

:construction: (feature/totalCV) #71 프로필 사진 완성

---

ItsME/Presentation/Common/Component/ProfileInfoComponent.swift
ItsME/Presentation/Common/Component/TotalUserInfoItemStackView.swift
ItsME/Presentation/Scenes/Home/HomeViewController.swift
ItsME/Presentation/Scenes/TotalCV/TotalCVViewController.swift

- #73 유저인포 컴포넌트 기능 구현
- 유저 정보 컴포넌트 글자 줄 제한 해제

:construction: :sparkles: (feature/totalCV) #73 유저인포 컴포넌트 기능 구현

---

ItsME/Presentation/Common/Component/TotalUserInfoItemStackView.swift
ItsME/Presentation/Scenes/EditProfile/EditProfileViewController.swift

- `TotalUserInfoItemStackView` 클래스를 `UserInfoItemStackView` 이름으로도 사용할 수 있게 구현

:zap: 클래스를 적절한 다른 이름으로 사용할 수 있게 구현

---

ItsME/Presentation/Scenes/TotalCV/TotalCVViewController.swift

:construction: :sparkles: (feature/totalCV) 학력 테이블뷰 생성 #76

---

ItsME.xcodeproj/project.pbxproj
ItsME/Repositories/CVRepository.swift
ItsME/Utils/DefaultJsonDecoder.swift

- DB 에서 데이터를 가져오는 중 발생하는 여러 문제들에 대한 로그가 전혀 없어서 문제 파악이 바로 안되었다.
- 새로 Decode 를 위한 래핑 클래스를 정의하여 DEBUG configuration 일때 로그가 찍히게함
```mermaid
flowchart LR
A{{JSON}}---B[decode 실패]--RELEASE-->C[throw error]
B--DEBUG-->D[/콘솔에 에러 원인 출력/]-->C
```

:zap: DB 에서 데이터를 가져오는 중 발생하는 에러를 콘솔에 출력하여 확인하기 위한 Decoder 클래스 생성

---

ItsME/Presentation/Common/Cells/CategoryCell.swift
ItsME/Presentation/Scenes/TotalCV/TotalCVViewController.swift
ItsME/Presentation/Scenes/TotalCV/TotalCVViewModel.swift
ItsME/Repositories/CVRepository.swift

- 카테고리 테이블 컴포넌트 생성
- 행에 맞는 내용이 오게끔 기능 구현
- 섹션에 대한 내용을 추가해주기만 하면 테이블 완성

섹션에 대한 작업 미완

---

ItsME.xcodeproj/project.pbxproj
ItsME/Presentation/Common/TableSection/CategoryHeaderView.swift
ItsME/Presentation/Common/TableSection/CategoryTitle.swift
ItsME/Presentation/Scenes/TotalCV/TotalCVViewController.swift
ItsME/Repositories/CVRepository.swift

- #87 카테고리 섹션 테이블 기능 완성
- 네비게이션 타이틀 모드 변경
- #85 의 리뷰에 대한 수정작업

섹션에 대한 작업 완료

---

ItsME/Presentation/Scenes/TotalCV/TotalCVViewController.swift

:recycle: (feature/totalCV) 새로운 변수를 생성하여 폰트 사이즈 통일

---

ItsME/Presentation/Common/Component/ProfileInfoComponent.swift
ItsME/Presentation/Scenes/Home/HomeViewController.swift

:recycle: (feature/fix) 다크모드 적용가능한 색상으로 변경

---

ItsME.xcodeproj/project.pbxproj
ItsME/Presentation/Scenes/TotalCV/TotalCVViewController.swift

수정 버튼 눌렀을 때 위에 기본정보들을 기본 레이아웃에서 삭제한 후에 새롭게 레이아웃 잡고
다시 원 상태로 돌아올 때 모든 레이아웃을 지웠다가 다시 처음 상태를 불러옴
- 버튼 클릭 전
- 버튼 클릭 후

:sparkles: :construction: (feature/totalCV) 수정 버튼 눌렀을 때 레이아웃 조정

---

ItsME/Entities/UserInfoItem.swift
ItsME/Presentation/Scenes/EditProfile/EditProfileViewController.swift
ItsME/Presentation/Scenes/EditProfile/EditProfileViewModel.swift
ItsME/Presentation/Scenes/EditProfile/EmailEditing/EmailEditingViewController.swift
ItsME/Presentation/Scenes/EditProfile/OtherItem/CommonView/Cell/ContentsInputCell.swift

- #105 완료
- ViewModel 로직 쪼금 리팩토링

:sparkles: 이메일 수정 화면 구현

---

ItsME.xcodeproj/project.pbxproj
ItsME/Presentation/Common/TableView/IntrinsicHeightTableView.swift
ItsME/Presentation/Common/TextView/IntrinsicHeightTextView.swift
ItsME/Presentation/Scenes/EditProfile/AddressEditing/AddressEditingViewController.swift
ItsME/Presentation/Scenes/EditProfile/EditProfileViewController.swift
ItsME/Presentation/Scenes/EditProfile/EditProfileViewModel.swift
ItsME/Presentation/Scenes/EditProfile/PhoneNumberEditing/PhoneNumberEditingViewController.swift
ItsME/Presentation/Scenes/Home/HomeViewController.swift

- 전화번호 수정 화면 구현
- 주소 수정 화면 구현
- IntrinsicHeightTextView 클래스 정의
- 프로필 수정 화면으로의 화면 전환 스타일 변경
- 홈으로 돌아갈 때 Alert 추가

프로필 정보 수정 화면 구현

---

ItsME/Presentation/Common/Cells/CategoryCell.swift
ItsME/Presentation/Common/Cells/CoverLetterCell.swift
ItsME/Presentation/Scenes/TotalCV/TotalCVViewController.swift

- 셀 사이 간격을 띄워져 보이기 위해 UIView를 두개 추가하여 띄워지게끔 설정
- setEdting함수를 활용한 수정 모드 적용

:sparkles: :zap: :construction: (feature/totalCV) 셀 사이 간격 조정 및 setEdting을 활용한 수정 모드 적용

---

ItsME/Presentation/Common/Component/ItemAddButton.swift
ItsME/Presentation/Scenes/ProfileEditing/AddressEditing/AddressEditingViewController.swift
ItsME/Presentation/Scenes/ProfileEditing/EmailEditing/EmailEditingViewController.swift
ItsME/Presentation/Scenes/ProfileEditing/OtherItem/CommonView/Cell/ContentsInputCell.swift
ItsME/Presentation/Scenes/ProfileEditing/OtherItem/CommonView/Cell/IconInputCell.swift
ItsME/Presentation/Scenes/ProfileEditing/OtherItem/NewOtherItem/NewOtherItemViewController.swift
ItsME/Presentation/Scenes/ProfileEditing/OtherItem/OtherItemEditing/OtherItemEditingViewController.swift
ItsME/Presentation/Scenes/ProfileEditing/PhoneNumberEditing/PhoneNumberEditingViewController.swift

- 프로필 수정 화면 관련 View: 다크 모드 대응
- #110 해결
- 항목추가 버튼 테두리 색상 설정

:lipstick: 다크 모드 대응 및 UI 개선

---

ItsME.xcodeproj/project.pbxproj
ItsME/Presentation/Common/Component/EditModeAddButton.swift
ItsME/Presentation/Scenes/TotalCV/TotalCVViewController.swift

:sparkles: :construction: (feature/totalCV) 항목 추가버튼 생성

---

ItsME.xcodeproj/project.pbxproj
ItsME/Presentation/Common/Component/EditModeAddButton.swift
ItsME/Presentation/Scenes/TotalCV/TotalCVViewController.swift

- EditModeAddButton 의존성 제거
- 버튼의 이미지 배치 조정과 역할에 따른 Title 조정

:art: :lipstick: (feature/totalCV) #118 EditModeAddButton 의존성 제거 및 버튼 조정

---

ItsME/Entities/CoverLetter.swift
ItsME/Entities/CoverLetterItem.swift
ItsME/Entities/Resume.swift
ItsME/Entities/ResumeCategory.swift
ItsME/Entities/ResumeItem.swift
ItsME/Presentation/Scenes/TotalCV/TotalCVViewController.swift
ItsME/Presentation/Scenes/TotalCV/TotalCVViewModel.swift

- `setEditng`을 이용한 delete 구현 (데이터베이스에 보내는 작업 미완)
- `moveRowAt` 이용한 셀 간의 이동 데이터 처리 미구현
- CoverLetter의 배열을 활용하기 위한 TotalCVViewModel 수정 ([CoverLetterItems] -> CoverLetter)

:construction: :sparkles: (feature/totalCV) #122, TotalCVViewModel 수정

---

ItsME.xcodeproj/project.pbxproj
ItsME/Presentation/Common/TableView/IntrinsicHeightTableView.swift
ItsME/Presentation/Scenes/ProfileEditing/AddressEditing/AddressEditingViewController.swift
ItsME/Presentation/Scenes/ProfileEditing/OtherItem/NewOtherItem/NewOtherItemViewController.swift
ItsME/Presentation/Scenes/ProfileEditing/OtherItem/OtherItemEditing/OtherItemEditingViewController.swift
ItsME/Utils/Extensions/Rx+Ext.swift
ItsME/Utils/Extensions/SnapKit+.swift
ItsME/Utils/Extensions/UIEdgeInsets+All.swift
ItsMEUITests/ItsMEUITests.swift

- [편집 화면 진입 시 키보드 올라오도록 구현](https://github.com/ILGOB/It-sME/commit/11c35ad2a32e7e2f44f3afd9a7ef9b91662853c7)
- [자동 높이 조절 테이블 뷰의 섹션이 2개 이상일 때 크기를 계산 못하는 부분 수정](https://github.com/ILGOB/It-sME/commit/c0912847f81d16a8ce5e7386d1e80a576c0e6d6f)
- [모든 방향에 Inset을 적용한 객체를 반환하는 유틸 함수 추가](https://github.com/ILGOB/It-sME/commit/ef94baab3ffb6601a43e492660765b35d38a2c50)
- [Rx: SharedSequence 대상으로도 mapToVoid() 함수를 사용할 수 있도록 구현](https://github.com/ILGOB/It-sME/commit/e03084f9e52f88f6563dcfb9a4252d2889103b1a)
- [SnapKit 편의 함수 정의](https://github.com/ILGOB/It-sME/commit/7302235b48b542ae9c2a3d1b961197b2ecbc49c8)
- [UITest 툴 이용해서 테스트하기 편한 환경 구성](https://github.com/ILGOB/It-sME/commit/bc952be160375a7b14463c668bb651d57aa6c0d8) #117 
https://user-images.githubusercontent.com/81426024/222368879-4255a721-f4ae-41c …

프로필 수정 화면 작업 & 버그 수정 & 편의 함수 추가

---

ItsME/Presentation/Scenes/TotalCV/TotalCVViewController.swift

- [행 이동할때 데이터 처리](https://github.com/ILGOB/It-sME/commit/c9f8ddc53bc373e8a677ea238061380bbf9166b8)
- [셀 이동시 섹션을 넘어갔을 때 이동이 안되게끔 하는 기능 구현](https://github.com/ILGOB/It-sME/commit/8c7f017d01901b4d6bb292449949624e5f2a8bcc)
https://user-images.githubusercontent.com/70786167/222636675-717c40e3-940c-42a2-9e34-4cf434afcd84.MOV

:sparkles: 테이블 셀 이동 관련 기능 추가

---

ItsME.xcodeproj/project.pbxproj
ItsME/Entities/EducationItem.swift
ItsME/Presentation/Common/Cells/TextFieldCell.swift
ItsME/Presentation/Common/PickerView/YearMonthPickerView.swift
ItsME/Presentation/Scenes/ProfileEditing/EducationEditing/Cells/PeriodInputCell.swift
ItsME/Presentation/Scenes/ProfileEditing/EducationEditing/Cells/YearMonthPickerCell.swift
ItsME/Presentation/Scenes/ProfileEditing/EducationEditing/EducationEditingViewController.swift
ItsME/Presentation/Scenes/ProfileEditing/EducationEditing/EducationEditingViewModel.swift
ItsME/Presentation/Scenes/ProfileEditing/ProfileEditingViewController.swift
ItsME/Presentation/Scenes/ProfileEditing/ProfileEditingViewModel.swift
ItsME/Utils/Extensions/YearMonthPickerView+Rx.swift
ItsME/Utils/YearMonthPickerViewDelegateProxy.swift

- EducationItem 엔티티에 입학, 졸업 날짜 관련 computed properties 추가
- [TextField 를 가지고 있는 Cell 정의](https://github.com/ILGOB/It-sME/commit/fcf095d2bd69c6e96e40be0590e01c5b450d682a)
- YearMonthPickerView 구현 & Rx 확장
- 70% 구현 완료
- 졸업일 선택 기능 작업중
다크 모드가 자연스럽게 되어버린...

공통 뷰 구현 & 학력 편집 화면 구현

---

ItsME.xcodeproj/project.pbxproj
ItsME/Entities/EducationItem.swift
ItsME/Presentation/Common/PickerView/YearMonthPickerView.swift
ItsME/Presentation/Scenes/ProfileEditing/EducationEditing/Cells/PeriodInputCell.swift
ItsME/Presentation/Scenes/ProfileEditing/EducationEditing/Cells/SchoolEnrollmentStatusCell.swift
ItsME/Presentation/Scenes/ProfileEditing/EducationEditing/EducationEditingViewController.swift
ItsME/Presentation/Scenes/ProfileEditing/EducationEditing/EducationEditingViewModel.swift
ItsME/Utils/Extensions/Array+SafeIndex.swift
ItsME/Utils/Extensions/Int+.swift
ItsMETests/ExtensionTests.swift

- [ifExists subscript 를 사용할 때 인덱스를 벗어났을경우 debugPrint() 함수로 "Out of index" 출력](https://github.com/ILGOB/It-sME/commit/d26f70a45bc1110707c07ed31436dc0a8460c55e)
- [현재 날짜 계산 로직 개선](https://github.com/ILGOB/It-sME/commit/e14cb33c2d5e7cb84fcd3e96d024f5adfd52c68d)
- [엔티티는 unwrapping 처리를 할 책임이 없다고 생각하여 unwrapping 과정 제거](https://github.com/ILGOB/It-sME/commit/2d2f270fced6ab61d7c2460df7d9aaded1b25034)
- [숫자 앞에 0을 붙여주는 Extension 함수 정의 + 테스트 케이스 작성](https://github.com/ILGOB/It-sME/commit/6a2fa7ee8129a9efa886fefec56d0204ef984579)
- [졸업일에 대한 PickerView 구현](https://github.com/ILGOB/It-sME/commit/0da91e0b623fda706bb3b2db0a82de45ae3073e6)
- 졸업 여부 선택 Cell 추가

공통 사항 개선, 구현 & 학력 편집 화면의 졸업일 선택 기능 구현

---

ItsME.xcodeproj/project.pbxproj
ItsME/Entities/ResumeItem.swift
ItsME/Presentation/Scenes/TotalCV/CVEditing/CategoryEditing/CategoryEditingViewController.swift
ItsME/Presentation/Scenes/TotalCV/CVEditing/CategoryEditing/CategoryEditingViewModel.swift
ItsME/Presentation/Scenes/TotalCV/CVEditing/CategoryEditing/CommonView/Cell/CategoryItemsCell.swift
ItsME/Presentation/Scenes/TotalCV/CVEditing/CategoryEditing/CommonView/Cell/PeriodCell.swift
ItsME/Presentation/Scenes/TotalCV/CVEditing/CoverLetterEditing/CommonView/CoverLetterItemCell.swift
ItsME/Presentation/Scenes/TotalCV/CVEditing/CoverLetterEditing/CoverLetterEditingViewController.swift
ItsME/Presentation/Scenes/TotalCV/CVEditing/CoverLetterEditing/CoverLetterEditingViewModel.swift
ItsME/Presentation/Scenes/TotalCV/TotalCVViewController.swift
ItsME/Presentation/Scenes/TotalCV/TotalCVViewModel.swift

- TextField 각각 수정 가능
- 설명 Cell은 TextField로 구현했을 때 잘리게 표현되어 TextView로 변경하는 작업
- #132
- 카테고리 편집
- 자기소개서 편집

카테고리 편집화면에서 카테고리 테이블 기능 구현(데이터 처리 기능 미완)

---

ItsME/Presentation/Common/Cells/TextViewCell.swift
ItsME/Presentation/Scenes/TotalCV/CVEditing/CategoryEditing/CategoryEditingViewController.swift
ItsME/Presentation/Scenes/TotalCV/TotalCVViewController.swift

- TableViewCell에 placeholder 기능 추가
- TotalCVViewController에서 EditMode일 때 cell 선택 시 잔상이 남던 효과 삭제

소소한 추가사항(TextView, TableViewCell)

---

ItsME.xcodeproj/project.pbxproj
ItsME.xcodeproj/xcshareddata/xcschemes/ItsME.xcscheme
ItsME/Repositories/UIDRepository.swift
ItsME/Utils/Extensions/OSStatus+ToReadableString.swift
ItsMETests/UIDRepositoryTests.swift

- UIDRepository 구현
- [관심 타겟에 대하여 코드 커버리지 활성화](https://github.com/ILGOB/It-sME/commit/061b71742f6614dfd84eb53e2d3bf2133959f232)
- 코드 커버리지란? https://zeddios.tistory.com/1141

:sparkles: Repository 구현

---

ItsME/Presentation/Common/Cells/TextViewCell.swift
ItsME/Presentation/Scenes/TotalCV/CVEditing/CategoryEditing/CategoryEditingViewController.swift
ItsME/Presentation/Scenes/TotalCV/CVEditing/CategoryEditing/CategoryEditingViewModel.swift
ItsME/Presentation/Scenes/TotalCV/TotalCVViewController.swift

- [⚡ (feature/totalCV) CategoryEditing 데이터 처리부분](https://github.com/ILGOB/It-sME/commit/d0b14ae1d05d5f3605dd7477c4c44b4ed4742f79)
- [💡 ♻️ 🎨 (feature/totalCV) 주석 추가 및 주석에 맞는 함수 위치조정](https://github.com/ILGOB/It-sME/commit/c0df7b47e7d9b2e60bffd6c580d1018f485844f1)
- [🎨 (feature/totalCV) TextViewCell의 placeholder 라벨을 따로 만들어 기능 추가](https://github.com/ILGOB/It-sME/commit/e5a97feee6a7429b8a0a8371324ff950eb378747)

CategoryEditing 데이터처리, TextViewCell의 Placeholder 기능 추가

---

ItsME.xcodeproj/project.pbxproj
ItsME/Presentation/Scenes/TotalCV/CVEditing/CategoryAdding/CategoryAddingViewController.swift
ItsME/Presentation/Scenes/TotalCV/CVEditing/ResumeItemEditing/ResumeItemEditingViewController.swift
ItsME/Presentation/Scenes/TotalCV/CVEditing/ResumeItemEditing/ResumeItemEditingViewModel.swift
ItsME/Presentation/Scenes/TotalCV/TotalCVViewController.swift

- Category 추가 뷰 적용 ( 데이터 처리 미완)
- 파일이름 변경 (CategoryAddingViewController, CategoryEditingViewController)
- Category -> ResumeItem으로 변경(좀 더 확실한 의미를 가지고 있게 하기위해)

:sparkles: :construction: :truck: (feature/totalCV) 카테고리 추가 View

---

ItsME.xcodeproj/project.pbxproj
ItsME/Presentation/Common/TableSection/CategoryHeaderView.swift
ItsME/Presentation/Scenes/TotalCV/CVEditing/CategoryAdding/CategoryAddingViewController.swift
ItsME/Presentation/Scenes/TotalCV/CVEditing/CategoryAdding/CategoryAddingViewModel.swift
ItsME/Presentation/Scenes/TotalCV/TotalCVViewController.swift
ItsME/Presentation/Scenes/TotalCV/TotalCVViewModel.swift

- 카테고리 추가 화면 데이터 처리 완성
- 텍스트 필드였던 카테고리 제목을 버튼으로 변경
https://user-images.githubusercontent.com/70786167/226835459-c5f97c2a-d578-416f-a125-1b8a0b7ea5a6.png width=300/>

:sparkles: (feature/totalCV) 카테고리 추가 화면 

---

ItsME.xcodeproj/project.pbxproj
ItsME/Application/AppLoginStatusManager.swift
ItsME/Presentation/Scenes/Login/LoginViewModel.swift
ItsME/Presentation/Scenes/ProfileEditing/OtherItem/OtherItemEditingViewModel.swift
ItsME/Presentation/Scenes/ProfileEditing/ProfileEditingViewModel.swift
ItsME/Repositories/UIDRepository.swift
ItsME/Utils/Extensions/AppLoginStatusManager+Rx.swift
ItsME/Utils/Extensions/Collection+isNotEmpty.swift
ItsMETests/UIDRepositoryTests.swift
Podfile
Podfile.lock

- 오타 수정
- Keychaining 라이브러리 설치
- `isNotEmpty` extention 추가

키체인 관리를 위한 라이브러리 도입 & 오타 수정

---

ItsME.xcodeproj/project.pbxproj
ItsME/Entities/CVInfo.swift
ItsME/Presentation/Common/TableSection/CategoryHeaderView.swift
ItsME/Presentation/Scenes/Home/HomeViewController.swift
ItsME/Presentation/Scenes/TotalCV/CVEditing/CategoryEditing/CategoryEditingViewController.swift
ItsME/Presentation/Scenes/TotalCV/CVEditing/CategoryEditing/CategoryEditingViewModel.swift
ItsME/Presentation/Scenes/TotalCV/CVEditing/CoverLetterEditing/CoverLetterEditingViewController.swift
ItsME/Presentation/Scenes/TotalCV/CVEditing/CoverLetterEditing/CoverLetterEditingViewModel.swift
ItsME/Presentation/Scenes/TotalCV/CVEditing/ResumeItemEditing/ResumeItemEditingViewController.swift
ItsME/Presentation/Scenes/TotalCV/CVEditing/ResumeItemEditing/ResumeItemEditingViewModel.swift
ItsME/Presentation/Scenes/TotalCV/TotalCVViewController.swift
ItsME/Presentation/Scenes/TotalCV/TotalCVViewModel.swift

TotalCVViewModel 완성

---

ItsME.xcodeproj/project.pbxproj
ItsME/Application/AppLoginStatusManager.swift
ItsME/Application/SceneDelegate.swift
ItsME/Entities/EducationItem.swift
ItsME/Entities/UserInfo.swift
ItsME/Entities/UserInfoItem.swift
ItsME/Presentation/Common/Cells/ContextMenuCell.swift
ItsME/Presentation/Scenes/Home/HomeViewModel.swift
ItsME/Presentation/Scenes/Login/LoginViewController.swift
ItsME/Presentation/Scenes/Login/LoginViewModel.swift
ItsME/Presentation/Scenes/ProfileEditing/EducationEditing/EducationEditingViewController.swift
ItsME/Presentation/Scenes/ProfileEditing/EducationEditing/EducationEditingViewModel.swift
ItsME/Presentation/Scenes/ProfileEditing/OtherItem/OtherItemEditingViewController.swift
ItsME/Presentation/Scenes/ProfileEditing/OtherItem/OtherItemEditingViewModel.swift
ItsME/Presentation/Scenes/ProfileEditing/ProfileEditingViewController.swift
ItsME/Presentation/Scenes/ProfileEditing/ProfileEditingViewModel.swift
ItsME/Presentation/Scenes/TotalCV/TotalCVViewModel.swift
ItsME/Repositories/CVRepository.swift
ItsME/Repositories/UIDRepository.swift
ItsME/Repositories/UserRepository.swift
ItsME/Resources/Info.plist
ItsME/Utils/ASAuthorizationControllerDelegateProxy.swift
ItsME/Utils/Extensions/AuthenticationServices+Rx.swift
ItsME/Utils/Extensions/FIRAuth+Rx.swift
ItsME/Utils/Extensions/FIRAuth+isLoggedIn.swift
ItsME/Utils/Extensions/Rx+Ext.swift
ItsME/Utils/Extensions/UIButton.Configuration+Then.swift
ItsME/Utils/Extensions/UIViewController+presentConfirmAlert.swift
ItsME/Utils/Hash.swift
ItsME/Utils/LoggedJsonDecoder.swift

- 로그아웃 버튼 추가 & 기능 구현 (https://itsme-ilgob-com.atlassian.net/browse/ME-17)(이거 연동 어케하는거지...)
- 애플 로그인 이용 시 로그인 상태 유지 구현
https://user-images.githubusercontent.com/81426024/229114189-804834ea-c2d8-405a-a962-2506bf09fe0c.mp4

파이어베이스 인증방식 도입

---

ItsME/Presentation/Common/AlertViewController/CommonAlertViewController.swift
ItsME/Presentation/Scenes/ProfileEditing/ProfileEditingViewController.swift
ItsME/Presentation/Scenes/TotalCV/TotalCVViewController.swift
ItsME/Repositories/Firebase/DatabaseReferenceManager.swift
Podfile
Podfile.lock

- [cvRef -> cvsRef 이름 적절하게 수정](https://github.com/ILGOB/It-sME/commit/c188998932993a030d3c004a2e79bb7006c6f12a)
- [AlertController 서브클래싱 사용 안하도록 변경](https://github.com/ILGOB/It-sME/commit/e40ea8e7a1bf9466853984195ca9dfafe414dbc5) #160

Firebase Cloud Storage 패키지 추가 & 코드 개선

---

ItsME.xcodeproj/project.pbxproj
ItsME/Entities/UserInfo.swift
ItsME/Presentation/Scenes/Home/HomeViewController.swift
ItsME/Presentation/Scenes/ProfileEditing/ProfileEditingViewController.swift
ItsME/Presentation/Scenes/ProfileEditing/ProfileEditingViewModel.swift
ItsME/Utils/Extensions/StorageReference+Rx.swift
ItsME/Utils/Extensions/UIImagePickerController+Rx.swift
ItsME/Utils/Path.swift
ItsME/Utils/UIImagePickerControllerDelegateProxy.swift

- [홈화면 프로필 사진 바인딩](https://github.com/ILGOB/It-sME/commit/f1cc8239770dfaba9f7a952edac0c45a40cd19ff)
- [프로필 사진 변경 기능 구현](https://github.com/ILGOB/It-sME/commit/4c2bbf93f681dbc94ed11805c1bee8e701b15ba5)
- Firebase storage 에 사진 저장 후, 저장된 사진의 path 를 유저 정보에 담아서 데이터베이스에 저장
- 이미지 크기 3MB 제한

:sparkles: 프로필 사진 변경 기능 구현 & 홈화면 프로필 사진 바인딩

---

ItsME.xcodeproj/project.pbxproj
ItsME/Data/Firebase/StoragePath.swift
ItsME/Data/Repositories/CVRepository.swift
ItsME/Data/Repositories/UserRepository.swift
ItsME/Entities/CVInfo.swift
ItsME/Presentation/Scenes/Home/HomeViewModel.swift
ItsME/Presentation/Scenes/ProfileEditing/ProfileEditingViewModel.swift
ItsME/Presentation/Scenes/TotalCV/TotalCVViewModel.swift
ItsME/Utils/Hash.swift

데이터 베이스 null 데이터 대응

---

ItsME.xcodeproj/project.pbxproj
ItsME/Data/Repositories/CVRepository.swift
ItsME/Entities/CVInfo.swift
ItsME/Presentation/Scenes/Home/CVAdding/CVAddViewController.swift
ItsME/Presentation/Scenes/Home/CVAdding/CVAddViewModel.swift
ItsME/Presentation/Scenes/Home/Component/AddCVButton.swift
ItsME/Presentation/Scenes/Home/HomeViewController.swift
ItsME/Presentation/Scenes/Home/HomeViewModel.swift
ItsME/Presentation/Scenes/TotalCV/TotalCVViewController.swift
ItsME/Presentation/Scenes/TotalCV/TotalCVViewModel.swift
ItsME/Resources/Assets.xcassets/테스트이미지.imageset/Contents.json

:sparkles: (feature/HomeView) CV 추가기능 구현(데이터 처리까지 테스트 완료)

---

ItsME.xcodeproj/project.pbxproj
ItsME/Data/Repositories/CVRepository.swift
ItsME/Presentation/Scenes/Home/CVAdding/CVAddViewController.swift
ItsME/Presentation/Scenes/Home/CVAdding/CVAddViewModel.swift
ItsME/Presentation/Scenes/Home/Component/AddCVButton.swift
ItsME/Presentation/Scenes/Home/HomeViewController.swift
ItsME/Presentation/Scenes/Home/HomeViewModel.swift
ItsME/Presentation/Scenes/TotalCV/TotalCVViewController.swift
ItsME/Presentation/Scenes/TotalCV/TotalCVViewModel.swift
ItsME/Resources/Assets.xcassets/테스트이미지.imageset/Contents.json
ItsME/Utils/Path.swift

Revert "Revert ":sparkles: (feature/HomeView) CV 추가기능 구현(데이터 처리까지 테스트 완료)""

---

ItsME/Presentation/Scenes/Home/HomeViewController.swift
ItsME/Presentation/Scenes/TotalCV/TotalCVViewModel.swift

:recycle: (feature/HomeView) 간단한 에러 해결

---

ItsME/Presentation/Scenes/Home/Component/AddCVButton.swift

- [ME-76](https://itsme-ilgob-com.atlassian.net/browse/ME-76) 해결

:adhesive_bandage: (ME-76) CV 추가 버튼 테두리 약간 잘리는 문제 해결

---

ItsME/Entities/UserInfoItem.swift

일단은 몇개 골라서 추가했습니다. 추가로 넣었으면 하는 아이콘이 있으면 코멘트로 달아주시거나 후에 이슈로 등록해주세요.

:lipstick: (ME-63) 프로필 기본 정보 입력시 선택 가능한 아이콘 추가

---

ItsME/Presentation/Common/Component/CVCard.swift
ItsME/Presentation/Common/TableSection/CategoryHeaderView.swift
ItsME/Presentation/Scenes/Home/Component/AddCVButton.swift
ItsME/Presentation/Scenes/Home/HomeViewController.swift
ItsME/Presentation/Scenes/TotalCV/TotalCVViewController.swift
Podfile
Podfile.lock

- SFSafeSymbol 라이브러리 도입
- 안쓰는 라이브러리 목록 제거(Keychaining)
- 라이브러리 버전 확실하게 명시
`pod install` 꼭 수행하여 `pod.lock` 파일의 CHECKSUM 값을 맞춰주세요!

[Me-82] 이슈 해결

---

ItsME/Presentation/Scenes/ProfileEditing/EducationEditing/EducationEditingViewController.swift

학력 편집 화면에서 키보드로 입력을 할때 사용성 불편한 부분 일부 해소

:iphone: (ME-88) 학력 편집 화면 스크롤 뷰 추가 및 키보드 show/hide 대응

---

ItsME.xcodeproj/project.pbxproj
ItsME/Data/Repositories/CVRepository.swift
ItsME/Data/Repositories/UserRepository.swift
ItsME/Presentation/Scenes/Login/LoginViewModel.swift
ItsME/Presentation/Scenes/ProfileEditing/ProfileEditingViewController.swift
ItsME/Presentation/Scenes/ProfileEditing/ProfileEditingViewModel.swift
ItsME/Utils/AuthProviderID.swift
ItsME/Utils/ItsMEError.swift
ItsME/Utils/ItsMEUtils.swift
ItsME/Utils/Reactive/BaseExtensions/FIRAuth+Rx.swift
ItsME/Utils/Reactive/Rx+Ext.swift
Podfile
Podfile.lock

- 카카오 계정 삭제 구현 완료
- 애플 로그인 계정 삭제 작업중

[Me-92] 카카오 로그인 시 계정 삭제 구현 완료

---

Podfile

:package: (develop) Pod 에서 발생하는 Dead Code Stripping 경고 뜨지 않도록 Podfile 수정

---

ItsME.xcodeproj/project.pbxproj
ItsME/Data/Repositories/UserProfileRepository.swift
ItsME/Entities/Education.swift
ItsME/Entities/UserBasicProfileInfo.swift
ItsME/Entities/UserProfile.swift
ItsME/Presentation/Common/Cells/EducationCell.swift
ItsME/Presentation/Common/Component/ProfileInfoComponent.swift
ItsME/Presentation/Common/Component/TotalUserInfoItemStackView.swift
ItsME/Presentation/Scenes/Home/HomeViewController.swift
ItsME/Presentation/Scenes/Home/HomeViewModel.swift
ItsME/Presentation/Scenes/Login/LoginViewModel.swift
ItsME/Presentation/Scenes/ProfileEditing/BirthdayEditing/BirthdayEditingViewController.swift
ItsME/Presentation/Scenes/ProfileEditing/CommonView/UserInfoItemCell.swift
ItsME/Presentation/Scenes/ProfileEditing/EducationEditing/EducationEditingViewModel.swift
ItsME/Presentation/Scenes/ProfileEditing/OtherItem/Cell/IconCell.swift
ItsME/Presentation/Scenes/ProfileEditing/OtherItem/Cell/IconInputCell.swift
ItsME/Presentation/Scenes/ProfileEditing/OtherItem/OtherItemEditingViewController.swift
ItsME/Presentation/Scenes/ProfileEditing/OtherItem/OtherItemEditingViewModel.swift
ItsME/Presentation/Scenes/ProfileEditing/ProfileEditingViewController.swift
ItsME/Presentation/Scenes/ProfileEditing/ProfileEditingViewModel.swift
ItsME/Presentation/Scenes/SignUp/SignUpViewModel.swift
ItsME/Presentation/Scenes/TotalCV/TotalCVViewController.swift
ItsME/Presentation/Scenes/TotalCV/TotalCVViewModel.swift

- `UserInfo` -> `UserProfile`
- `UserInfoItem` -> `UserBasicProfileInfo`
- `UserRepository` -> `UserProfileRepository`
- `EducationItem` -> Education`
- `hasUserInfo` -> `hasUserProfile`
- `getUserInfo` -> `getUserProfile`
- `saveUserInfo` -> `saveUserProfile`
- `deleteUserInfo` -> `deleteUserProfile`

클래스, 함수명 리팩토링

---

ItsME.xcodeproj/project.pbxproj
ItsME/Presentation/Common/Cells/EducationCell.swift
ItsME/Presentation/Scenes/ProfileEditing/ProfileEditingViewController.swift
ItsME/Presentation/Scenes/ProfileEditing/ProfileEditingViewModel.swift
ItsME/Utils/Extensions/CGPoint+.swift
ItsME/Utils/Extensions/UIView+.swift

- 길게 눌러서 순서를 변경할 수 있는 기능 추가
https://user-images.githubusercontent.com/81426024/235314805-77c862e4-7f30-42d9-96e3-cc287821f235.mp4

[Me-89] 프로필 편집 화면에서 학력 항목 순서 변경 기능 구현

---

ItsME/Presentation/Scenes/Home/HomeViewController.swift

- 이력서 제목 편집 아이콘 변경 (iOS 16+ -> iOS 13+)

:lipstick: (ME-97) 이력서 제목 편집 아이콘 변경 (iOS 13+)

---

ItsME/Presentation/Scenes/ProfileEditing/ProfileEditingViewModel.swift
ItsME/Utils/Rx/Rx+Ext.swift

:zap: (develop) 자주 사용하는 Rx 메소드를 래핑하는 편리 메소드 정의

---

ItsME/Presentation/Common/Component/ProfileInfoComponent.swift

- Then 라이브러리 적용 
- 내용이 비어있을 때 placeholder가 보이도록 변경

:zap: (ME-119) Then 라이브러리 적용 및 내용이 비어있을 때 placeholder가 보이도록 변경

---

ItsME.xcodeproj/project.pbxproj
ItsME/Presentation/Scenes/ProfileEditing/CommonView/MovableEducationCell.swift
ItsME/Presentation/Scenes/ProfileEditing/ProfileEditingViewController.swift

`EducationCell` 에 추가했던 Symbol 을 프로필 수정 화면에서만 보이도록 변경

:bug: (ME-120) 이력서 화면에서도 학력 정보에 `line3` symbol 보이는 문제 해결

---

ItsME.xcodeproj/project.pbxproj
ItsME/Presentation/Scenes/ProfileEditing/PhoneNumberEditing/PhoneNumberEditingViewController.swift
ItsME/Utils/ItsMEUtils.swift
ItsMETestsWithoutApp/ItsMEFunctionsTests.swift

- 하이픈 문자를 넣어주는 함수 정의
- 테스트 코드 작성
- ViewController 에서 적용
https://user-images.githubusercontent.com/81426024/236135985-1f758834-ce39-41b2-81fb-b8c3526bae94.mp4

:sparkles: (ME-50) 전화번호 입력시 하이픈(-) 문자 자동으로 추가되는 기능 구현

---

ItsME.xcodeproj/project.pbxproj
ItsME/Presentation/Scenes/Home/CVEditing/CVEditViewController.swift
ItsME/Presentation/Scenes/Home/CVEditing/CVEditViewModel.swift
ItsME/Presentation/Scenes/Home/HomeViewController.swift
ItsME/Presentation/Scenes/ProfileEditing/AddressEditing/AddressEditingViewController.swift
ItsME/Presentation/Scenes/ProfileEditing/AddressEditing/AddressEditingViewModel.swift
ItsME/Presentation/Scenes/ProfileEditing/EducationEditing/EducationEditingViewController.swift
ItsME/Presentation/Scenes/ProfileEditing/EmailEditing/EmailEditingViewController.swift
ItsME/Presentation/Scenes/ProfileEditing/EmailEditing/EmailEditingViewModel.swift
ItsME/Presentation/Scenes/ProfileEditing/OtherItem/OtherItemEditingViewController.swift
ItsME/Presentation/Scenes/ProfileEditing/PhoneNumberEditing/PhoneNumberEditingViewController.swift
ItsME/Presentation/Scenes/ProfileEditing/PhoneNumberEditing/PhoneNumberEditingViewModel.swift
ItsME/Presentation/Scenes/ProfileEditing/ProfileEditingViewController.swift
ItsME/Presentation/Scenes/ProfileEditing/ProfileEditingViewModel.swift
ItsME/Presentation/Scenes/TotalCV/CVEditing/CategoryEditing/CategoryEditingViewController.swift
ItsME/Presentation/Scenes/TotalCV/CVEditing/CoverLetterEditing/CoverLetterEditingViewController.swift
ItsME/Presentation/Scenes/TotalCV/CVEditing/ResumeItemEditing/ResumeItemEditingViewController.swift

대부분의 입력 화면에서 중요 입력 필드가 비어있으면 완료 버튼이 비활성화 되도록 구현

[Me-57] 입력 필드가 비어있을때 완료 버튼 비활성화

---

ItsME.xcodeproj/project.pbxproj
ItsME/Application/SceneDelegate.swift
ItsME/Presentation/Scenes/ProfileEditing/ProfileEditingViewModel.swift
ItsME/UseCases/LogoutUseCase.swift
ItsME/UseCases/LogoutWithAppleUseCase.swift

- LogoutWithAppleUseCase 추가하여 애플 로그아웃 처리 개선

:zap: (ME-102) 애플 아이디 사용 중단 처리 로직 개선

---

ItsME/Presentation/Scenes/ProfileEditing/PhoneNumberEditing/PhoneNumberEditingViewController.swift
ItsME/Presentation/Scenes/SignUp/SignUpViewController.swift

- SignUpViewController 에 적용
- 기존 로직 리팩토링

:zap: (ME-50) 전화번호 입력시 하이픈 자동 입력 구현

---

ItsME/Data/Repositories/CVRepository.swift
ItsME/Data/Repositories/UserProfileRepository.swift
ItsME/Presentation/Scenes/ProfileEditing/ProfileEditingViewModel.swift
ItsME/UseCases/LogoutUseCase.swift

- RepositoryProtocol 정의
- ViewModel 이 Protocol 을 의존하도록 변경

:recycle: (unit-test/view-model) 테스트할 수 있도록 리팩토링

---

ItsME.xcodeproj/project.pbxproj
ItsME/Application/DIContainer.swift
ItsME/Application/SceneDelegate.swift
ItsME/Presentation/Scenes/Home/CVEditing/CVEditViewModel.swift
ItsME/Presentation/Scenes/Home/HomeViewController.swift
ItsME/Presentation/Scenes/Home/HomeViewModel.swift
ItsME/Presentation/Scenes/Login/LoginViewController.swift
ItsME/Presentation/Scenes/Login/LoginViewModel.swift
ItsME/Presentation/Scenes/ProfileEditing/ProfileEditingViewController.swift
ItsME/Presentation/Scenes/ProfileEditing/ProfileEditingViewModel.swift
ItsME/Presentation/Scenes/SignUp/SignUpViewController.swift
ItsME/Presentation/Scenes/TotalCV/TotalCVViewModel.swift
ItsME/UseCases/DeleteAccountUseCase.swift
ItsME/UseCases/GetAppleIDRefreshTokenFromKeychainUseCase.swift
ItsME/UseCases/GetNicknameAndEmailForKakaoUseCase.swift
ItsME/UseCases/Normal/DeleteAccountUseCase.swift
ItsME/UseCases/Normal/GetCurrentAuthProviderIDUseCase.swift
ItsME/UseCases/Normal/GetNicknameAndEmailForKakaoUseCase.swift
ItsME/UseCases/Normal/LoginWithAppleUseCase.swift
ItsME/UseCases/Normal/LoginWithKakaoUseCase.swift
ItsME/UseCases/Normal/LogoutUseCase.swift
ItsME/UseCases/Normal/RevokeAppleIDRefreshTokenUseCase.swift
ItsME/UseCases/Normal/SaveAppleIDRefreshTokenToKeychainUseCase.swift
ItsME/UseCases/Normal/SignInToFirebaseUseCase.swift

:zap: (ME-110) DIContainer 정의

---

ItsME/Data/Network/Apple/AppleRESTAPI+Rx.swift
ItsME/Data/Network/Apple/AppleRESTAPI.swift
ItsME/UseCases/RevokeAppleIDRefreshTokenUseCase.swift
ItsME/UseCases/SaveAppleIDRefreshTokenToKeychainUseCase.swift

:recycle: (unit-test/use-case) UseCase 테스트를 위한 리팩토링

---

.github/workflows/buildAndTest.yml

Update buildAndTest.yml
- 캐시 적용
- 빌드 & 테스트 명령어 확실하게 지정

:rocket: :zap: (develop) build and test workflow 개선

---

ItsME/Application/DIContainer.swift
ItsME/Application/SceneDelegate.swift
ItsME/Data/Repositories/UserProfileRepository.swift
ItsME/UseCases/DeleteAccountUseCase.swift
ItsME/UseCases/GetAppleIDRefreshTokenFromKeychainUseCase.swift
ItsME/UseCases/GetCurrentAuthProviderIDUseCase.swift
ItsME/UseCases/GetNicknameAndEmailForKakaoUseCase.swift
ItsME/UseCases/GetProfileImageUseCase.swift
ItsME/UseCases/LoginWithAppleUseCase.swift
ItsME/UseCases/LoginWithKakaoUseCase.swift
ItsME/UseCases/LogoutUseCase.swift
ItsME/UseCases/LogoutWithAppleUseCase.swift
ItsME/UseCases/RevokeAppleIDRefreshTokenUseCase.swift
ItsME/UseCases/SaveAppleIDRefreshTokenToKeychainUseCase.swift
ItsME/UseCases/SaveProfileImageUseCase.swift
ItsME/UseCases/SignInToFirebaseUseCase.swift

- 테스트를 위한 Test doubles 를 만들 수 없기 때문에 싱글톤에서 변경

:zap: (improve) 싱글톤 패턴에서 공유 인스턴스로 변경

---

ItsMEUITests/ItsMEUITests.swift

:test_tube: UI Object 확인을 위해 대기하는 시간 증가

---

ItsME.xcodeproj/project.pbxproj
ItsME/Application/DIContainer.swift
ItsME/Application/SceneDelegate.swift
ItsME/Presentation/Scenes/Home/HomeViewController.swift
ItsME/Presentation/Scenes/ProfileEditing/ProfileEditingViewModel.swift
ItsME/UseCases/GetUserProfileUseCase.swift
ItsME/UseCases/SaveUserProfileUseCase.swift
ItsMETests/TestDoubles/DeleteAccountUseCaseMock.swift
ItsMETests/TestDoubles/GetProfileImageUseCaseMock.swift
ItsMETests/TestDoubles/GetUserProfileUseCaseMock.swift
ItsMETests/TestDoubles/LogoutUseCaseMock.swift
ItsMETests/TestDoubles/SaveProfileImageUseCaseMock.swift
ItsMETests/TestDoubles/SaveUserProfileUseCaseMock.swift
ItsMETests/Utils/TestScheduler+.swift
ItsMETests/Utils/XCTest+Rx+.swift
ItsMETests/ViewModel/ProfileEditingViewModelTests.swift

하위 작업
- ViewModel 의 Repository 의존성을 없애는 리팩토링
- 변수이름 리팩토링 & 오타 수정
- 파일/그룹 정렬

:test_tube: ProfileEditingViewModel 테스트 케이스 추가

---

ItsME.xcodeproj/project.pbxproj
ItsME/Presentation/Scenes/ProfileEditing/PhoneNumberEditing/PhoneNumberEditingViewController.swift
ItsME/Presentation/Scenes/SignUp/SignUpViewController.swift
Podfile
Podfile.lock

[전화번호 입력 화면의 완료 버튼 활성화되지 않는 문제 수정](https://github.com/ILGOB/It-sME/commit/87017fca8746d1d9389473b1ee9258325f03b4b2)

v1.1.1 배포 - 버그 수정
